### ISSUE TITLE
Support other python versions

### ISSUE THREAD

**Issue by Changaco** [Praisebetoscience/openshift-cartridge-python-3.5#1]
Are you open to that? If so, please add a license to the project, then I'll make a pull request to add python 2.7.

**Comment by Praisebetoscience** [comment]
If you want to sure, but there's already a standard 2.7 cartridge supported by Openshift.

**Comment by Praisebetoscience** [comment]
I added an MIT license to it.

**Comment by Changaco** [comment]
The official python cartridge is heavier, based on `mod_wsgi`. I want to use a lite one that only installs python.
